聚类分析，数学基础，算法： https://zhuanlan.zhihu.com/p/37856153
聚类分析，spss操作： https://zhuanlan.zhihu.com/p/31579236

因子分析，数学基础： https://blog.csdn.net/qq_29831163/article/details/88918422
（求特征根“入”： https://wenku.baidu.com/view/8d7f6248640e52ea551810a6f524ccbff121cac7.html）
（求正交矩阵： https://baike.baidu.com/item/%E6%AD%A3%E4%BA%A4%E7%9F%A9%E9%98%B5）
因子分析，spss操作： https://www.douban.com/group/topic/37869176/

主成分分析：https://blog.csdn.net/qq_29831163/article/details/89577292
（主成分多重共线，因子互不交集）